runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /bot.*
  script: bot.app

- url: /.*
  script: main.app
  

libraries:
- name: PIL
  version: "1.1.7"
- name: ssl
  version: latest
